from . import vendorguard_constants
from . import vendorguard_fraud_flag
from . import vendorguard_bank_change_log
from . import res_partner
from . import res_partner_bank
from . import account_move
from . import purchase_order
from . import vendorguard_demo_scenario
from . import vendorguard_settings
from . import vendorguard_ask_wizard
