BANK_CHANGE_RECENT_DAYS = 14
STRUCTURING_WINDOW_DAYS = 30
STRUCTURING_THRESHOLD = 10000.0
LOOKALIKE_SIMILARITY_THRESHOLD = 0.85

SEVERITY_SCORE_PENALTY = {
    'critical': 40,
    'high': 25,
    'medium': 10,
    'low': 5,
}

BENFORD_MIN_SAMPLE_SIZE = 25
BENFORD_MAD_CLOSE = 0.004
BENFORD_MAD_ACCEPTABLE = 0.008
BENFORD_MAD_MARGINAL = 0.012
# Chi-square goodness-of-fit critical value at alpha=0.05, 8 degrees of freedom (9 leading digits - 1)
BENFORD_CHI_SQUARE_CRITICAL = 15.507

THREE_WAY_MATCH_QTY_TOLERANCE = 0.01
